"""
랜덤 취미 추천 웹앱 - 취미 데이터 모듈
50개 이상의 다양한 취미 데이터를 관리합니다.
"""

# 카테고리 정보 (이모지, 색상)
CATEGORIES = {
    "창작": {"emoji": "🎨", "color": "#FF6B6B"},
    "운동": {"emoji": "🏃", "color": "#4ECDC4"},
    "실내": {"emoji": "🏠", "color": "#45B7D1"},
    "실외": {"emoji": "🌿", "color": "#96CEB4"},
    "사교": {"emoji": "🤝", "color": "#FFEAA7"},
    "학습": {"emoji": "📚", "color": "#DDA0DD"},
}

HOBBIES = [
    # ── 창작 (10개) ──
    {
        "name": "수채화 그리기",
        "category": "창작",
        "difficulty": 2,
        "cost": 2,
        "indoor": True,
        "description": "물과 물감으로 부드러운 색감의 그림을 그리는 예술 활동입니다.",
        "supplies": ["수채화 물감", "붓 세트", "수채화 용지", "팔레트"],
        "emoji": "🎨",
        "tip": "처음엔 유튜브 튜토리얼을 따라하면 좋아요!",
    },
    {
        "name": "뜨개질",
        "category": "창작",
        "difficulty": 2,
        "cost": 1,
        "indoor": True,
        "description": "실과 바늘로 모자, 목도리, 인형 등을 만드는 핸드메이드 활동입니다.",
        "supplies": ["뜨개질 바늘", "털실", "코바늘(선택)"],
        "emoji": "🧶",
        "tip": "코바늘이 대바늘보다 입문하기 쉬워요!",
    },
    {
        "name": "캘리그라피",
        "category": "창작",
        "difficulty": 2,
        "cost": 1,
        "indoor": True,
        "description": "아름다운 손글씨를 연습하고 작품을 만드는 예술 활동입니다.",
        "supplies": ["캘리그라피 펜", "연습 용지", "먹물"],
        "emoji": "✒️",
        "tip": "매일 10분씩 기본 획 연습부터 시작해보세요!",
    },
    {
        "name": "사진 촬영",
        "category": "창작",
        "difficulty": 3,
        "cost": 3,
        "indoor": False,
        "description": "카메라나 스마트폰으로 일상과 풍경의 아름다움을 담는 활동입니다.",
        "supplies": ["카메라 또는 스마트폰", "삼각대(선택)"],
        "emoji": "📷",
        "tip": "스마트폰 카메라로도 충분히 시작할 수 있어요!",
    },
    {
        "name": "도자기 만들기",
        "category": "창작",
        "difficulty": 3,
        "cost": 3,
        "indoor": True,
        "description": "흙을 빚어 그릇, 컵, 화분 등을 만드는 공예 활동입니다.",
        "supplies": ["원데이 클래스 수강권"],
        "emoji": "🏺",
        "tip": "원데이 클래스로 체험해보고, 마음에 들면 정규반을 등록하세요!",
    },
    {
        "name": "레진 공예",
        "category": "창작",
        "difficulty": 2,
        "cost": 2,
        "indoor": True,
        "description": "투명한 레진으로 키링, 악세사리, 소품을 만드는 공예 활동입니다.",
        "supplies": ["UV 레진", "UV 램프", "실리콘 몰드", "장식 재료"],
        "emoji": "💎",
        "tip": "환기가 잘 되는 곳에서 작업하세요!",
    },
    {
        "name": "디지털 드로잉",
        "category": "창작",
        "difficulty": 3,
        "cost": 3,
        "indoor": True,
        "description": "태블릿과 펜으로 디지털 일러스트를 그리는 활동입니다.",
        "supplies": ["태블릿", "스타일러스 펜", "드로잉 앱"],
        "emoji": "🖌️",
        "tip": "무료 앱 '메디방페인트'로 시작해보세요!",
    },
    {
        "name": "향수 만들기",
        "category": "창작",
        "difficulty": 2,
        "cost": 3,
        "indoor": True,
        "description": "다양한 향료를 블렌딩해 나만의 향수를 만드는 활동입니다.",
        "supplies": ["향료 세트", "무수 에탄올", "스포이트", "향수병"],
        "emoji": "🧴",
        "tip": "조향 원데이 클래스로 기본을 배워보세요!",
    },
    {
        "name": "미니어처 만들기",
        "category": "창작",
        "difficulty": 4,
        "cost": 2,
        "indoor": True,
        "description": "작은 세계를 정교하게 만들어내는 섬세한 공예 활동입니다.",
        "supplies": ["미니어처 키트", "접착제", "핀셋", "아크릴 물감"],
        "emoji": "🏡",
        "tip": "초보자용 DIY 키트부터 시작하면 좋아요!",
    },
    {
        "name": "캔들 만들기",
        "category": "창작",
        "difficulty": 1,
        "cost": 2,
        "indoor": True,
        "description": "소이왁스와 향료로 나만의 향초를 만드는 힐링 활동입니다.",
        "supplies": ["소이왁스", "향료", "심지", "용기", "온도계"],
        "emoji": "🕯️",
        "tip": "소이왁스는 천연 재료라 초보자에게 추천해요!",
    },
    # ── 운동 (9개) ──
    {
        "name": "러닝",
        "category": "운동",
        "difficulty": 1,
        "cost": 1,
        "indoor": False,
        "description": "가장 간단하면서도 효과적인 유산소 운동입니다.",
        "supplies": ["러닝화", "운동복"],
        "emoji": "🏃",
        "tip": "처음엔 걷기와 달리기를 번갈아 하는 인터벌로 시작하세요!",
    },
    {
        "name": "클라이밍",
        "category": "운동",
        "difficulty": 3,
        "cost": 3,
        "indoor": True,
        "description": "인공 암벽을 오르며 전신 근력과 문제 해결력을 키우는 스포츠입니다.",
        "supplies": ["클라이밍화", "초크백(선택)"],
        "emoji": "🧗",
        "tip": "볼더링부터 시작하면 장비 부담이 적어요!",
    },
    {
        "name": "요가",
        "category": "운동",
        "difficulty": 2,
        "cost": 1,
        "indoor": True,
        "description": "몸과 마음의 균형을 찾는 명상과 스트레칭 활동입니다.",
        "supplies": ["요가 매트", "편한 운동복"],
        "emoji": "🧘",
        "tip": "유튜브 '요가위드에이드리언' 채널이 초보자에게 좋아요!",
    },
    {
        "name": "배드민턴",
        "category": "운동",
        "difficulty": 2,
        "cost": 1,
        "indoor": False,
        "description": "라켓과 셔틀콕으로 즐기는 누구나 쉽게 시작할 수 있는 스포츠입니다.",
        "supplies": ["배드민턴 라켓", "셔틀콕", "운동화"],
        "emoji": "🏸",
        "tip": "동네 배드민턴 동호회에 가입하면 파트너 걱정 없어요!",
    },
    {
        "name": "수영",
        "category": "운동",
        "difficulty": 2,
        "cost": 2,
        "indoor": True,
        "description": "전신 운동이면서 관절에 부담이 적은 건강한 스포츠입니다.",
        "supplies": ["수영복", "수경", "수모"],
        "emoji": "🏊",
        "tip": "지역 스포츠센터 강습반에 등록하면 체계적으로 배울 수 있어요!",
    },
    {
        "name": "필라테스",
        "category": "운동",
        "difficulty": 2,
        "cost": 3,
        "indoor": True,
        "description": "코어 근력 강화와 자세 교정에 효과적인 운동입니다.",
        "supplies": ["운동복", "필라테스 매트"],
        "emoji": "🤸",
        "tip": "기구 필라테스보다 매트 필라테스가 가격이 저렴해요!",
    },
    {
        "name": "탁구",
        "category": "운동",
        "difficulty": 2,
        "cost": 1,
        "indoor": True,
        "description": "빠른 반사 신경과 순발력을 기를 수 있는 실내 스포츠입니다.",
        "supplies": ["탁구 라켓", "탁구공"],
        "emoji": "🏓",
        "tip": "동네 탁구장에서 저렴하게 즐길 수 있어요!",
    },
    {
        "name": "테니스",
        "category": "운동",
        "difficulty": 3,
        "cost": 3,
        "indoor": False,
        "description": "전신 운동과 전략이 결합된 세련된 라켓 스포츠입니다.",
        "supplies": ["테니스 라켓", "테니스공", "테니스화"],
        "emoji": "🎾",
        "tip": "요즘 테니스 레슨이 인기! 그룹 레슨으로 시작하면 부담이 적어요!",
    },
    {
        "name": "줄넘기",
        "category": "운동",
        "difficulty": 1,
        "cost": 1,
        "indoor": False,
        "description": "장소에 구애받지 않고 할 수 있는 효율적인 유산소 운동입니다.",
        "supplies": ["줄넘기"],
        "emoji": "⏭️",
        "tip": "하루 10분만 해도 칼로리 소모가 엄청나요!",
    },
    # ── 실내 (9개) ──
    {
        "name": "퍼즐 맞추기",
        "category": "실내",
        "difficulty": 1,
        "cost": 1,
        "indoor": True,
        "description": "조각을 하나씩 맞추며 집중력과 인내심을 기르는 활동입니다.",
        "supplies": ["직소 퍼즐"],
        "emoji": "🧩",
        "tip": "500피스부터 시작해서 점점 늘려보세요!",
    },
    {
        "name": "보드게임",
        "category": "실내",
        "difficulty": 1,
        "cost": 2,
        "indoor": True,
        "description": "친구, 가족과 함께 즐기는 다양한 전략/파티 게임입니다.",
        "supplies": ["보드게임 (스플렌더, 루미큐브 등)"],
        "emoji": "🎲",
        "tip": "보드게임 카페에서 여러 게임을 체험해보세요!",
    },
    {
        "name": "독서",
        "category": "실내",
        "difficulty": 1,
        "cost": 1,
        "indoor": True,
        "description": "책을 통해 새로운 세계를 경험하고 지식을 넓히는 활동입니다.",
        "supplies": ["책 또는 전자책 리더기"],
        "emoji": "📖",
        "tip": "도서관을 이용하면 무료로 다양한 책을 읽을 수 있어요!",
    },
    {
        "name": "요리",
        "category": "실내",
        "difficulty": 2,
        "cost": 2,
        "indoor": True,
        "description": "다양한 레시피를 시도하며 맛있는 음식을 만드는 활동입니다.",
        "supplies": ["기본 조리도구", "식재료"],
        "emoji": "🍳",
        "tip": "'만개의 레시피' 앱에서 초보용 레시피를 찾아보세요!",
    },
    {
        "name": "베이킹",
        "category": "실내",
        "difficulty": 3,
        "cost": 2,
        "indoor": True,
        "description": "쿠키, 케이크, 빵 등을 직접 굽는 달콤한 취미입니다.",
        "supplies": ["오븐", "밀가루", "버터", "설탕", "베이킹 도구"],
        "emoji": "🧁",
        "tip": "노오븐 베이킹 레시피로 시작하면 장비 부담이 적어요!",
    },
    {
        "name": "영화 감상",
        "category": "실내",
        "difficulty": 1,
        "cost": 1,
        "indoor": True,
        "description": "다양한 장르의 영화를 감상하며 문화적 소양을 넓히는 활동입니다.",
        "supplies": ["OTT 구독 (넷플릭스, 왓챠 등)"],
        "emoji": "🎬",
        "tip": "테마별 영화 리스트를 만들어 보는 것도 재미있어요!",
    },
    {
        "name": "홈카페",
        "category": "실내",
        "difficulty": 2,
        "cost": 2,
        "indoor": True,
        "description": "집에서 다양한 커피와 음료를 만들어 즐기는 활동입니다.",
        "supplies": ["커피 원두", "핸드드립 도구 또는 모카포트", "컵"],
        "emoji": "☕",
        "tip": "핸드드립부터 시작하면 진입 비용이 낮아요!",
    },
    {
        "name": "레고 조립",
        "category": "실내",
        "difficulty": 2,
        "cost": 3,
        "indoor": True,
        "description": "블록을 조립하며 창의력과 집중력을 키우는 활동입니다.",
        "supplies": ["레고 세트"],
        "emoji": "🧱",
        "tip": "관심 있는 테마(건축물, 꽃 등)의 세트를 골라보세요!",
    },
    {
        "name": "게임",
        "category": "실내",
        "difficulty": 1,
        "cost": 2,
        "indoor": True,
        "description": "PC, 콘솔, 모바일로 다양한 게임을 즐기는 활동입니다.",
        "supplies": ["PC 또는 게임기", "게임 타이틀"],
        "emoji": "🎮",
        "tip": "무료 게임도 많으니 스팀 무료 게임부터 탐색해보세요!",
    },
    # ── 실외 (8개) ──
    {
        "name": "등산",
        "category": "실외",
        "difficulty": 2,
        "cost": 1,
        "indoor": False,
        "description": "산을 오르며 자연을 만끽하고 체력을 기르는 활동입니다.",
        "supplies": ["등산화", "등산복", "배낭", "물"],
        "emoji": "⛰️",
        "tip": "서울 근교 낮은 산(북한산 둘레길 등)부터 시작하세요!",
    },
    {
        "name": "캠핑",
        "category": "실외",
        "difficulty": 2,
        "cost": 3,
        "indoor": False,
        "description": "자연 속에서 텐트를 치고 여유로운 시간을 보내는 활동입니다.",
        "supplies": ["텐트", "침낭", "버너", "코펠", "랜턴"],
        "emoji": "⛺",
        "tip": "글램핑장에서 먼저 체험해보고 장비를 마련하세요!",
    },
    {
        "name": "낚시",
        "category": "실외",
        "difficulty": 2,
        "cost": 2,
        "indoor": False,
        "description": "강, 바다, 저수지에서 물고기를 잡는 여유로운 아웃도어 활동입니다.",
        "supplies": ["낚싯대", "릴", "미끼", "낚시 의자"],
        "emoji": "🎣",
        "tip": "실내 낚시카페에서 먼저 체험해보세요!",
    },
    {
        "name": "자전거 타기",
        "category": "실외",
        "difficulty": 1,
        "cost": 2,
        "indoor": False,
        "description": "자전거를 타며 경치를 즐기고 건강도 챙기는 활동입니다.",
        "supplies": ["자전거", "헬멧", "자물쇠"],
        "emoji": "🚴",
        "tip": "따릉이로 시작해서, 마음에 들면 자전거를 구매하세요!",
    },
    {
        "name": "플로깅",
        "category": "실외",
        "difficulty": 1,
        "cost": 1,
        "indoor": False,
        "description": "조깅하면서 쓰레기를 줍는 환경 보호 + 운동 활동입니다.",
        "supplies": ["장갑", "쓰레기봉투", "운동화"],
        "emoji": "🌍",
        "tip": "SNS에 인증하면 동기부여가 되고 환경 의식도 높일 수 있어요!",
    },
    {
        "name": "산책 & 도시 탐험",
        "category": "실외",
        "difficulty": 1,
        "cost": 1,
        "indoor": False,
        "description": "동네나 새로운 도시를 걸으며 숨은 명소를 발견하는 활동입니다.",
        "supplies": ["편한 운동화", "카메라(선택)"],
        "emoji": "🚶",
        "tip": "'걷기 좋은 길' 앱으로 코스를 찾아보세요!",
    },
    {
        "name": "러닝 크루",
        "category": "실외",
        "difficulty": 2,
        "cost": 1,
        "indoor": False,
        "description": "함께 달리는 크루에 참여해 동기부여와 사교를 동시에 즐기는 활동입니다.",
        "supplies": ["러닝화", "운동복"],
        "emoji": "👟",
        "tip": "인스타그램에서 지역 러닝 크루를 검색해보세요!",
    },
    {
        "name": "서핑",
        "category": "실외",
        "difficulty": 4,
        "cost": 3,
        "indoor": False,
        "description": "파도 위에서 보드를 타는 짜릿한 해양 스포츠입니다.",
        "supplies": ["서핑 레슨 수강권"],
        "emoji": "🏄",
        "tip": "양양 서핑 레슨은 장비 대여 포함이라 처음 시작하기 좋아요!",
    },
    # ── 사교 (8개) ──
    {
        "name": "뮤지컬 관람",
        "category": "사교",
        "difficulty": 1,
        "cost": 3,
        "indoor": True,
        "description": "화려한 무대, 음악, 연기가 어우러진 공연을 감상하는 문화 활동입니다.",
        "supplies": ["공연 티켓"],
        "emoji": "🎭",
        "tip": "인터파크·멜론티켓에서 할인 이벤트를 자주 확인하세요! 대학로에서 소규모 뮤지컬도 추천!",
    },
    {
        "name": "독서 모임",
        "category": "사교",
        "difficulty": 1,
        "cost": 1,
        "indoor": True,
        "description": "같은 책을 읽고 서로의 생각을 나누는 소통형 취미입니다.",
        "supplies": ["지정 도서"],
        "emoji": "📚",
        "tip": "트레바리, 클래스101 등 플랫폼에서 다양한 모임을 찾을 수 있어요!",
    },
    {
        "name": "봉사 활동",
        "category": "사교",
        "difficulty": 1,
        "cost": 1,
        "indoor": False,
        "description": "지역 사회에 도움을 주며 보람을 느끼는 활동입니다.",
        "supplies": ["편한 복장"],
        "emoji": "💝",
        "tip": "1365자원봉사포털에서 다양한 봉사활동을 검색할 수 있어요!",
    },
    {
        "name": "와인 모임",
        "category": "사교",
        "difficulty": 2,
        "cost": 3,
        "indoor": True,
        "description": "다양한 와인을 시음하며 지식을 쌓고 사람들과 교류하는 활동입니다.",
        "supplies": ["와인잔(선택)"],
        "emoji": "🍷",
        "tip": "마트에서 1~2만 원대 와인부터 도전해보세요!",
    },
    {
        "name": "동호회 활동",
        "category": "사교",
        "difficulty": 1,
        "cost": 1,
        "indoor": False,
        "description": "같은 관심사를 가진 사람들과 함께 활동하는 커뮤니티입니다.",
        "supplies": ["활동에 따라 다름"],
        "emoji": "👥",
        "tip": "소모임 앱이나 네이버 카페에서 관심 분야 동호회를 찾아보세요!",
    },
    {
        "name": "노래방",
        "category": "사교",
        "difficulty": 1,
        "cost": 1,
        "indoor": True,
        "description": "좋아하는 노래를 마음껏 부르며 스트레스를 해소하는 활동입니다.",
        "supplies": ["없음"],
        "emoji": "🎤",
        "tip": "코인노래방이면 혼자서도 부담 없이 즐길 수 있어요!",
    },
    {
        "name": "전시회 관람",
        "category": "사교",
        "difficulty": 1,
        "cost": 2,
        "indoor": True,
        "description": "미술관, 박물관의 전시를 감상하며 문화적 안목을 넓히는 활동입니다.",
        "supplies": ["전시 티켓"],
        "emoji": "🖼️",
        "tip": "국립중앙박물관은 상설전시가 무료예요!",
    },
    {
        "name": "여행 계획 세우기",
        "category": "사교",
        "difficulty": 1,
        "cost": 1,
        "indoor": True,
        "description": "다음 여행지를 조사하고 계획을 세우는 설레는 활동입니다.",
        "supplies": ["노트 또는 여행 앱"],
        "emoji": "✈️",
        "tip": "구글 맵으로 가보고 싶은 장소를 저장해두면 편해요!",
    },
    # ── 학습 (9개) ──
    {
        "name": "파이썬 공부",
        "category": "학습",
        "difficulty": 3,
        "cost": 1,
        "indoor": True,
        "description": "세계에서 가장 인기 있는 프로그래밍 언어를 배우며 자동화, 데이터 분석, 웹 개발 등 무한한 가능성을 열어보세요.",
        "supplies": ["노트북 또는 PC", "인터넷"],
        "emoji": "🐍",
        "tip": "점프 투 파이썬(무료 온라인 책)이나 Codecademy로 시작해보세요!",
    },
    {
        "name": "외국어 공부",
        "category": "학습",
        "difficulty": 4,
        "cost": 1,
        "indoor": True,
        "description": "새로운 언어를 배우며 세계를 넓히는 도전적인 활동입니다.",
        "supplies": ["교재 또는 언어 학습 앱"],
        "emoji": "🌏",
        "tip": "듀오링고 앱으로 매일 5분씩 꾸준히 해보세요!",
    },
    {
        "name": "악기 연주 (기타)",
        "category": "학습",
        "difficulty": 3,
        "cost": 2,
        "indoor": True,
        "description": "기타를 배우며 좋아하는 노래를 직접 연주하는 활동입니다.",
        "supplies": ["어쿠스틱 기타", "기타 피크", "튜너"],
        "emoji": "🎸",
        "tip": "유튜브 '기타치는 상근이' 채널이 초보자에게 좋아요!",
    },
    {
        "name": "악기 연주 (피아노)",
        "category": "학습",
        "difficulty": 3,
        "cost": 3,
        "indoor": True,
        "description": "피아노를 배우며 클래식부터 팝까지 다양한 곡을 연주하는 활동입니다.",
        "supplies": ["전자 피아노 또는 키보드"],
        "emoji": "🎹",
        "tip": "Simply Piano 앱으로 독학이 가능해요!",
    },
    {
        "name": "악기 연주 (우쿨렐레)",
        "category": "학습",
        "difficulty": 1,
        "cost": 1,
        "indoor": True,
        "description": "작고 가벼운 우쿨렐레로 쉽고 즐겁게 음악을 배우는 활동입니다.",
        "supplies": ["우쿨렐레", "튜너"],
        "emoji": "🪕",
        "tip": "4개 코드만 배우면 수십 곡을 연주할 수 있어요!",
    },
    {
        "name": "천문학 관측",
        "category": "학습",
        "difficulty": 2,
        "cost": 1,
        "indoor": False,
        "description": "밤하늘의 별과 행성을 관측하며 우주에 대해 배우는 활동입니다.",
        "supplies": ["별자리 앱 (Star Walk)", "쌍안경(선택)"],
        "emoji": "🔭",
        "tip": "스마트폰 앱 'Star Walk'로 밤하늘을 비춰보세요!",
    },
    {
        "name": "블로그 운영",
        "category": "학습",
        "difficulty": 2,
        "cost": 1,
        "indoor": True,
        "description": "글을 쓰며 생각을 정리하고 지식을 공유하는 활동입니다.",
        "supplies": ["노트북 또는 PC", "인터넷"],
        "emoji": "✍️",
        "tip": "네이버 블로그나 브런치로 시작해보세요!",
    },
    {
        "name": "주식 투자 공부",
        "category": "학습",
        "difficulty": 4,
        "cost": 1,
        "indoor": True,
        "description": "경제와 주식 시장을 공부하며 재테크 능력을 기르는 활동입니다.",
        "supplies": ["투자 입문서", "증권 앱"],
        "emoji": "📈",
        "tip": "모의투자로 실전 감각을 먼저 키워보세요!",
    },
    {
        "name": "명상",
        "category": "학습",
        "difficulty": 1,
        "cost": 1,
        "indoor": True,
        "description": "마음을 가라앉히고 내면에 집중하며 스트레스를 해소하는 활동입니다.",
        "supplies": ["명상 앱 (마보, 캄)"],
        "emoji": "🧘",
        "tip": "하루 5분 호흡 명상부터 시작해보세요!",
    },
]
